# Series df[series]

## 2. Pandas Series: Access & Selection

In [24]:

import pandas as pd
import seaborn as sns

# Load Titanic dataset
df = sns.load_dataset('titanic')

In [25]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

### 1. Label-Based & Positional Access

### df['age'].at[label]

In [26]:
df['age'].at[0]

22.0

In [27]:
df['sex'].at[2]

'female'

In [28]:
df['age'].at[5]

nan

### df['age'].iat[position]

In [29]:
df['age'].iat[10]

4.0

In [30]:
df['fare'].iat[13]

31.275

### df['age'].loc[label]

In [31]:
df['age'].loc[12]

20.0

In [32]:
df['pclass'].loc[[2,4,5]] + df['age'].loc[[2,4,5]]

2    29.0
4    38.0
5     NaN
dtype: float64

In [33]:
df.loc[0, 'age']

22.0

In [34]:
print(df.loc[[0,2,15,6,10,11], 'age'])

0     22.0
2     26.0
15    55.0
6     54.0
10     4.0
11    58.0
Name: age, dtype: float64

In [35]:
df.loc[0, ['age', 'fare', 'sex']]

age     22.0
fare    7.25
sex     male
Name: 0, dtype: object

In [36]:
df.loc[[1, 3, 5, 10], ['sex', 'age', 'fare']]

       sex   age     fare
1   female  38.0  71.2833
3   female  35.0  53.1000
5     male   NaN   8.4583
10  female   4.0  16.7000

In [37]:
df.loc[0:4, 'age':'fare']

    age  sibsp  parch     fare
0  22.0      1      0   7.2500
1  38.0      1      0  71.2833
2  26.0      0      0   7.9250
3  35.0      1      0  53.1000
4  35.0      0      0   8.0500

In [38]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [39]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [40]:
# Single Row, Single Column : df.loc[row_label, column_label]
df.loc[10, 'age']

4.0

In [41]:
# Multiple Rows, Single Column: df.loc[[row_label1, row_label2], column_label]
df.loc[[10, 20, 30], 'age']

10     4.0
20    35.0
30    40.0
Name: age, dtype: float64

In [42]:
# 3. Single Row, Multiple Columns: df.loc[row_label, [column_label1, column_label2]]
df.loc[2, ['age', 'fare', 'pclass', 'who']]

age        26.0
fare      7.925
pclass        3
who       woman
Name: 2, dtype: object

### 2. Value Retrieval & Conversion

In [43]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [44]:
df['age'].get(0)

22.0

In [45]:
df['fare'].get(2)

7.925

In [46]:
df['age'].iloc[[0]].item()

22.0

In [47]:
df['fare'].array[:10]

<NumpyExtensionArray>
[7.25, 71.2833, 7.925, 53.1, 8.05, 8.4583, 51.8625, 21.075, 11.1333, 30.0708]
Length: 10, dtype: float64

In [48]:
df['age'].items

<bound method Series.items of 0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64>

In [49]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [50]:
for column, value in df['age'].items():
    print(column, value)
    if column >= 4:
        break

0 22.0
1 38.0
2 26.0
3 35.0
4 35.0

In [51]:
df['age'].keys()

RangeIndex(start=0, stop=891, step=1)

In [52]:
df['age'].values.tolist()

[22.0,
 38.0,
 26.0,
 35.0,
 35.0,
 nan,
 54.0,
 2.0,
 27.0,
 14.0,
 4.0,
 58.0,
 20.0,
 39.0,
 14.0,
 55.0,
 2.0,
 nan,
 31.0,
 nan,
 35.0,
 34.0,
 15.0,
 28.0,
 8.0,
 38.0,
 nan,
 19.0,
 nan,
 nan,
 40.0,
 nan,
 nan,
 66.0,
 28.0,
 42.0,
 nan,
 21.0,
 18.0,
 14.0,
 40.0,
 27.0,
 nan,
 3.0,
 19.0,
 nan,
 nan,
 nan,
 nan,
 18.0,
 7.0,
 21.0,
 49.0,
 29.0,
 65.0,
 nan,
 21.0,
 28.5,
 5.0,
 11.0,
 22.0,
 38.0,
 45.0,
 4.0,
 nan,
 nan,
 29.0,
 19.0,
 17.0,
 26.0,
 32.0,
 16.0,
 21.0,
 26.0,
 32.0,
 25.0,
 nan,
 nan,
 0.83,
 30.0,
 22.0,
 29.0,
 nan,
 28.0,
 17.0,
 33.0,
 16.0,
 nan,
 23.0,
 24.0,
 29.0,
 20.0,
 46.0,
 26.0,
 59.0,
 nan,
 71.0,
 23.0,
 34.0,
 34.0,
 28.0,
 nan,
 21.0,
 33.0,
 37.0,
 28.0,
 21.0,
 nan,
 38.0,
 nan,
 47.0,
 14.5,
 22.0,
 20.0,
 17.0,
 21.0,
 70.5,
 29.0,
 24.0,
 2.0,
 21.0,
 nan,
 32.5,
 32.5,
 54.0,
 12.0,
 nan,
 24.0,
 nan,
 45.0,
 33.0,
 20.0,
 47.0,
 29.0,
 25.0,
 23.0,
 19.0,
 37.0,
 16.0,
 24.0,
 nan,
 22.0,
 24.0,
 19.0,
 18.0,
 19.0,
 27.0,
 9.0,
 36.5,
 42.0,
 51.0,
 22.0,
 55.5,
 40.5,
 nan,
 51.0,
 16.0,
 30.0,
 nan,
 nan,
 44.0,
 40.0,
 26.0,
 17.0,
 1.0,
 9.0,
 nan,
 45.0,
 nan,
 28.0,
 61.0,
 4.0,
 1.0,
 21.0,
 56.0,
 18.0,
 nan,
 50.0,
 30.0,
 36.0,
 nan,
 nan,
 9.0,
 1.0,
 4.0,
 nan,
 nan,
 45.0,
 40.0,
 36.0,
 32.0,
 19.0,
 19.0,
 3.0,
 44.0,
 58.0,
 nan,
 42.0,
 nan,
 24.0,
 28.0,
 nan,
 34.0,
 45.5,
 18.0,
 2.0,
 32.0,
 26.0,
 16.0,
 40.0,
 24.0,
 35.0,
 22.0,
 30.0,
 nan,
 31.0,
 27.0,
 42.0,
 32.0,
 30.0,
 16.0,
 27.0,
 51.0,
 nan,
 38.0,
 22.0,
 19.0,
 20.5,
 18.0,
 nan,
 35.0,
 29.0,
 59.0,
 5.0,
 24.0,
 nan,
 44.0,
 8.0,
 19.0,
 33.0,
 nan,
 nan,
 29.0,
 22.0,
 30.0,
 44.0,
 25.0,
 24.0,
 37.0,
 54.0,
 nan,
 29.0,
 62.0,
 30.0,
 41.0,
 29.0,
 nan,
 30.0,
 35.0,
 50.0,
 nan,
 3.0,
 52.0,
 40.0,
 nan,
 36.0,
 16.0,
 25.0,
 58.0,
 35.0,
 nan,
 25.0,
 41.0,
 37.0,
 nan,
 63.0,
 45.0,
 nan,
 7.0,
 35.0,
 65.0,
 28.0,
 16.0,
 19.0,
 nan,
 33.0,
 30.0,
 22.0,
 42.0,
 22.0,
 26.0,
 19.0,
 36.0,
 24.0,
 24.0,
 nan,
 23.5,
 2.0,
 nan,
 50.0,
 nan,
 nan,
 19.0,
 nan,
 nan,
 0.92,
 nan,
 17.0,
 30.0,
 30.0,
 24.0,
 18.0,
 26.0,
 28.0,
 43.0,
 26.0,
 24.0,
 54.0,
 31.0,
 40.0,
 22.0,
 27.0,
 30.0,
 22.0,
 nan,
 36.0,
 61.0,
 36.0,
 31.0,
 16.0,
 nan,
 45.5,
 38.0,
 16.0,
 nan,
 nan,
 29.0,
 41.0,
 45.0,
 45.0,
 2.0,
 24.0,
 28.0,
 25.0,
 36.0,
 24.0,
 40.0,
 nan,
 3.0,
 42.0,
 23.0,
 nan,
 15.0,
 25.0,
 nan,
 28.0,
 22.0,
 38.0,
 nan,
 nan,
 40.0,
 29.0,
 45.0,
 35.0,
 nan,
 30.0,
 60.0,
 nan,
 nan,
 24.0,
 25.0,
 18.0,
 19.0,
 22.0,
 3.0,
 nan,
 22.0,
 27.0,
 20.0,
 19.0,
 42.0,
 1.0,
 32.0,
 35.0,
 nan,
 18.0,
 1.0,
 36.0,
 nan,
 17.0,
 36.0,
 21.0,
 28.0,
 23.0,
 24.0,
 22.0,
 31.0,
 46.0,
 23.0,
 28.0,
 39.0,
 26.0,
 21.0,
 28.0,
 20.0,
 34.0,
 51.0,
 3.0,
 21.0,
 nan,
 nan,
 nan,
 33.0,
 nan,
 44.0,
 nan,
 34.0,
 18.0,
 30.0,
 10.0,
 nan,
 21.0,
 29.0,
 28.0,
 18.0,
 nan,
 28.0,
 19.0,
 nan,
 32.0,
 28.0,
 nan,
 42.0,
 17.0,
 50.0,
 14.0,
 21.0,
 24.0,
 64.0,
 31.0,
 45.0,
 20.0,
 25.0,
 28.0,
 nan,
 4.0,
 13.0,
 34.0,
 5.0,
 52.0,
 36.0,
 nan,
 30.0,
 49.0,
 nan,
 29.0,
 65.0,
 nan,
 50.0,
 nan,
 48.0,
 34.0,
 47.0,
 48.0,
 nan,
 38.0,
 nan,
 56.0,
 nan,
 0.75,
 nan,
 38.0,
 33.0,
 23.0,
 22.0,
 nan,
 34.0,
 29.0,
 22.0,
 2.0,
 9.0,
 nan,
 50.0,
 63.0,
 25.0,
 nan,
 35.0,
 58.0,
 30.0,
 9.0,
 nan,
 21.0,
 55.0,
 71.0,
 21.0,
 nan,
 54.0,
 nan,
 25.0,
 24.0,
 17.0,
 21.0,
 nan,
 37.0,
 16.0,
 18.0,
 33.0,
 nan,
 28.0,
 26.0,
 29.0,
 nan,
 36.0,
 54.0,
 24.0,
 47.0,
 34.0,
 nan,
 36.0,
 32.0,
 30.0,
 22.0,
 nan,
 44.0,
 nan,
 40.5,
 50.0,
 nan,
 39.0,
 23.0,
 2.0,
 nan,
 17.0,
 nan,
 30.0,
 7.0,
 45.0,
 30.0,
 nan,
 22.0,
 36.0,
 9.0,
 11.0,
 32.0,
 50.0,
 64.0,
 19.0,
 nan,
 33.0,
 8.0,
 17.0,
 27.0,
 nan,
 22.0,
 22.0,
 62.0,
 48.0,
 nan,
 39.0,
 36.0,
 nan,
 40.0,
 28.0,
 nan,
 nan,
 24.0,
 19.0,
 29.0,
 nan,
 32.0,
 62.0,
 53.0,
 36.0,
 nan,
 16.0,
 19.0,
 34.0,
 39.0,
 nan,
 32.0,
 25.0,
 39.0,
 54.0,
 36.0,
 nan,
 18.0,
 47.0,
 60.0,
 22.0,
 nan,
 35.0,
 52.0,
 47.0,
 nan,
 37.0,
 36.0,
 nan,
 49.0,
 nan,
 49.0,
 24.0,
 nan,
 nan,
 44.0,
 35.0,
 36.0,
 30.0,
 27.0,
 22.0,
 40.0,
 39.0,
 nan,
 nan,
 nan,
 35.0,
 24.0,
 34.0,
 26.0,
 4.0,
 26.0,
 27.0,
 42.0,
 20.0,
 21.0,
 21.0,
 61.0,
 57.0,
 21.0,
 26.0,
 nan,
 80.0,
 51.0,
 32.0,
 nan,
 9.0,
 28.0,
 32.0,
 31.0,
 41.0,
 nan,
 20.0,
 24.0,
 2.0,
 nan,
 0.75,
 48.0,
 19.0,
 56.0,
 nan,
 23.0,
 nan,
 18.0,
 21.0,
 nan,
 18.0,
 24.0,
 nan,
 32.0,
 23.0,
 58.0,
 50.0,
 40.0,
 47.0,
 36.0,
 20.0,
 32.0,
 25.0,
 nan,
 43.0,
 nan,
 40.0,
 31.0,
 70.0,
 31.0,
 nan,
 18.0,
 24.5,
 18.0,
 43.0,
 36.0,
 nan,
 27.0,
 20.0,
 14.0,
 60.0,
 25.0,
 14.0,
 19.0,
 18.0,
 15.0,
 31.0,
 4.0,
 nan,
 25.0,
 60.0,
 52.0,
 44.0,
 nan,
 49.0,
 42.0,
 18.0,
 35.0,
 18.0,
 25.0,
 26.0,
 39.0,
 45.0,
 42.0,
 22.0,
 nan,
 24.0,
 nan,
 48.0,
 29.0,
 52.0,
 19.0,
 38.0,
 27.0,
 nan,
 33.0,
 6.0,
 17.0,
 34.0,
 50.0,
 27.0,
 20.0,
 30.0,
 nan,
 25.0,
 25.0,
 29.0,
 11.0,
 nan,
 23.0,
 23.0,
 28.5,
 48.0,
 35.0,
 nan,
 nan,
 nan,
 36.0,
 21.0,
 24.0,
 31.0,
 70.0,
 16.0,
 30.0,
 19.0,
 31.0,
 4.0,
 6.0,
 33.0,
 23.0,
 48.0,
 0.67,
 28.0,
 18.0,
 34.0,
 33.0,
 nan,
 41.0,
 20.0,
 36.0,
 16.0,
 51.0,
 nan,
 30.5,
 nan,
 32.0,
 24.0,
 48.0,
 57.0,
 nan,
 54.0,
 18.0,
 nan,
 5.0,
 nan,
 43.0,
 13.0,
 17.0,
 29.0,
 nan,
 25.0,
 25.0,
 18.0,
 8.0,
 1.0,
 46.0,
 nan,
 16.0,
 nan,
 nan,
 25.0,
 39.0,
 49.0,
 31.0,
 30.0,
 30.0,
 34.0,
 31.0,
 11.0,
 0.42,
 27.0,
 31.0,
 39.0,
 18.0,
 39.0,
 33.0,
 26.0,
 39.0,
 35.0,
 6.0,
 30.5,
 nan,
 23.0,
 31.0,
 43.0,
 10.0,
 52.0,
 27.0,
 38.0,
 27.0,
 2.0,
 nan,
 nan,
 1.0,
 nan,
 62.0,
 15.0,
 0.83,
 nan,
 23.0,
 18.0,
 39.0,
 21.0,
 nan,
 32.0,
 nan,
 20.0,
 16.0,
 30.0,
 34.5,
 17.0,
 42.0,
 nan,
 35.0,
 28.0,
 nan,
 4.0,
 74.0,
 9.0,
 16.0,
 44.0,
 18.0,
 45.0,
 51.0,
 24.0,
 nan,
 41.0,
 21.0,
 48.0,
 nan,
 24.0,
 42.0,
 27.0,
 31.0,
 nan,
 4.0,
 26.0,
 47.0,
 33.0,
 47.0,
 28.0,
 15.0,
 20.0,
 19.0,
 nan,
 56.0,
 25.0,
 33.0,
 22.0,
 28.0,
 25.0,
 39.0,
 27.0,
 19.0,
 nan,
 26.0,
 32.0]

### 3. Data Removal & Iteration

In [53]:
val = df['age'].pop(0)
print(val)

22.0

In [54]:
for i, val in df['age'].items():
    print(i, val)
    if i >= 4:
        break

1 38.0
2 26.0
3 35.0
4 35.0

### 4. Advanced Selection

In [67]:
df['age'].xs(12)

20.0