# Series df[series]

In [ ]:
from onedrive_loader import files, load

ModuleNotFoundError: No module named 'onedrive_loader'

In [2]:
files()

['financial_transactions_dataset_analytics_kaggle',
 'nhs-waiting-list-analytics_data',
 'portfolio-01-nhs-financial-analytics',
 'Portfolio-22-Financial-Performance-Analytics-Model',
 'region_electric_hourly_time_series',
 'SalesForecast',
 'sundry_data_sources']

In [5]:
dataset_folder1 = 'sundry_data_sources'
dataset_folder2 = 'nhs-waiting-list-analytics_data'
dataset_folder3 = 'Portfolio-22-Financial-Performance-Analytics-Model'

In [10]:
files(dataset_folder3)

['Financial Sample.xlsx']

In [4]:
df = load(dataset_folder,"uk_smoking_data.csv")

In [5]:
df

,gender,age,marital_status,highest_qualification,nationality,ethnicity,gross_income,region,smoke,amt_weekends,amt_weekdays,type
0,Male,38,Divorced,No Qualification,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
1,Female,42,Single,No Qualification,British,White,"Under 2,600",The North,Yes,12.0,12.0,Packets
2,Male,40,Married,Degree,English,White,"28,600 to 36,400",The North,No,NaN,NaN,NaN
3,Female,40,Married,Degree,English,White,"10,400 to 15,600",The North,No,NaN,NaN,NaN
4,Female,39,Married,GCSE/O Level,British,White,"2,600 to 5,200",The North,No,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1686,Male,22,Single,No Qualification,Scottish,White,"2,600 to 5,200",Scotland,No,NaN,NaN,NaN
1687,Female,49,Divorced,Other/Sub Degree,English,White,"2,600 to 5,200",Scotland,Yes,20.0,20.0,Hand-Rolled
1688,Male,45,Married,Other/Sub Degree,Scottish,White,"5,200 to 10,400",Scotland,No,NaN,NaN,NaN
1689,Female,51,Married,No Qualification,English,White,"2,600 to 5,200",Scotland,Yes,20.0,20.0,Packets
1690,Male,31,Married,Degree,Scottish,White,"10,400 to 15,600",Scotland,No,NaN,NaN,NaN

In [10]:
nhs = 'portfolio-01-nhs-financial-analytics'
files(nhs)

['dim_financial_year.csv',
 'dim_trust.csv',
 'expenditure_breakdown.csv',
 'expenditure_detail.csv',
 'ie_summary.csv',
 'income_detail.csv',
 'kpis.csv',
 'sector_benchmarks.csv',
 'workforce.csv']

In [11]:
files('portfolio-01-nhs-financial-analytics')

['dim_financial_year.csv',
 'dim_trust.csv',
 'expenditure_breakdown.csv',
 'expenditure_detail.csv',
 'ie_summary.csv',
 'income_detail.csv',
 'kpis.csv',
 'sector_benchmarks.csv',
 'workforce.csv']

In [12]:
df = load(file)

FileNotFoundError: OneDrive could not open 'TeslimDataLakes/portfolio-01-nhs-financial-analytics' (HTTP 404):

In [9]:
import pandas as pd

## 1. Pandas Series: Structure

In [2]:
import pandas as pd
import seaborn as sns

# Load dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

### 1. Basic Series Properties

In [3]:
df['age'].index

RangeIndex(start=0, stop=891, step=1)

In [4]:
df['age'].name

'age'

In [5]:
df['age'].dtype

dtype('float64')

In [5]:
df['age'].dtypes

dtype('float64')

In [6]:
df['age'].shape

(891,)

In [7]:
df['age'].ndim

1

In [8]:
df['age'].size

891

In [9]:
df['age'].values[:5]

array([22., 38., 26., 35., 35.])

In [10]:
df['age'].array[:5]

<NumpyExtensionArray>
[22.0, 38.0, 26.0, 35.0, 35.0]
Length: 5, dtype: float64

### 2. Boolean Checks

In [11]:
df['age'].empty

False

In [12]:
df['age'].hasnans

True

In [13]:
df['age'].isna().sum()

np.int64(177)

### 3. Advanced Attributes (Less Common)

In [14]:
df['age'].flags

In [15]:
df['age'].set_flags(allows_duplicate_labels=False)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [16]:
df['age'].attrs

{}